# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('total_score', models.FloatField(null=True)),
                ('food_score', models.FloatField(null=True)),
                ('service_score', models.FloatField(null=True)),
                ('value_score', models.FloatField(null=True)),
                ('ambience_score', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sgfood_app.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_or_neg', models.IntegerField()),
                ('tag_name', models.CharField(choices=[('S', 'SERVICE'), ('F', 'FOOD'), ('V', 'VALUE'), ('A', 'AMBIENCE')], default='A', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tag',
            field=models.ManyToManyField(null=True, to='sgfood_app.Tag'),
        ),
    ]
