# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgfood_app', '0003_auto_20180321_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
