# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgfood_app', '0006_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tag',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
